#pragma once
#include <cstdint>

enum EntityType : int16_t {
	ENTITY_NONE = 0,
	ENTITY_PLAYER = 1,
	ENTITY_ITEM = 2,
	ENTITY_LIGHTNING_BOLT = 3,
	// Mob types
	ENTITY_MOB_CREEPER = 150,
	ENTITY_MOB_SKELETON = 151,
	ENTITY_MOB_SPIDER = 152,
	ENTITY_MOB_GIANT_ZOMBIE = 153,
	ENTITY_MOB_ZOMBIE = 154,
	ENTITY_MOB_SLIME = 155,
	ENTITY_MOB_GHAST = 156,
	ENTITY_MOB_PIG_ZOMBIE = 157,
	ENTITY_MOB_PIG = 190,
	ENTITY_MOB_SHEEP = 191,
	ENTITY_MOB_COW = 192,
	ENTITY_MOB_CHICKEN = 193,
	ENTITY_MOB_SQUID = 194,
	ENTITY_MOB_WOLF = 195,
	// Object types
	ENTITY_OBJECT_BOAT = 201,
	ENTITY_OBJECT_MINECART = 210,
	ENTITY_OBJECT_MINECART_CHEST = 211,
	ENTITY_OBJECT_MINECART_FURNACE = 212,
	ENTITY_OBJECT_TNT_PRIMED = 250,
	ENTITY_OBJECT_ARROW = 260,
	ENTITY_OBJECT_SNOWBALL = 261,
	ENTITY_OBJECT_EGG = 262,
	ENTITY_OBJECT_FALLING_SAND = 270,
	ENTITY_OBJECT_FALLING_GRAVEL = 271,
	ENTITY_OBJECT_FISHING_BOBBER = 290,
};
