/*
 * Copyright (c) 2026, Pixel Brush <pixelbrush.dev>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 *
*/

// This file is primarily used by commands, so someone doesn't need to remember all the ids
// The labels chosen here will match those used by modern Minecraft,
// as those are the ones most people are likely the know best.
// It will deviate a little if the modern label doesn't fit the old block (e.g. "oak_planks" VS just "planks")

#pragma once
#include "../enums/blocks.h"
#include "../enums/items.h"
#include "../base_types.h"
#include <unordered_map>
#include <string>

// NOTE: Don't use outside of this!
struct SmallerItemStruct {
    ItemId id;
    int8_t meta;
};

// NOTE: There's probably better ways to do this, but this one's easy to manage for now.
const std::unordered_map<std::string, SmallerItemStruct> IDENTIFIER_TO_ID = {
    { "air", {BLOCK_AIR, 0} },
    { "stone", {BLOCK_STONE, 0} },
    { "grass_block", {BLOCK_GRASS, 0} },
    { "dirt", {BLOCK_DIRT, 0} },
    { "cobblestone", {BLOCK_COBBLESTONE, 0} },
    { "planks", {BLOCK_PLANKS, 0} },
    // Saplings
    { "sapling", {BLOCK_SAPLING, 0} },
    { "oak_sapling", {BLOCK_SAPLING, 0} },
    { "spruce_sapling", {BLOCK_SAPLING, 1} },
    { "birch_sapling", {BLOCK_SAPLING, 2} },
    { "bedrock", {BLOCK_BEDROCK, 0} },
    { "flowing_water", {BLOCK_WATER_FLOWING, 0} },
    { "water", {BLOCK_WATER_STILL, 0} },
    { "flowing_lava", {BLOCK_LAVA_FLOWING, 0} },
    { "lava", {BLOCK_LAVA_STILL, 0} },
    { "sand", {BLOCK_SAND, 0} },
    { "gravel", {BLOCK_GRAVEL, 0} },
    { "gold_ore", {BLOCK_ORE_GOLD, 0} },
    { "iron_ore", {BLOCK_ORE_IRON, 0} },
    { "coal_ore", {BLOCK_ORE_COAL, 0} },
    // Logs
    { "log", {BLOCK_LOG, 0} },
    { "oak_log", {BLOCK_LOG, 0} },
    { "spruce_log", {BLOCK_LOG, 1} },
    { "birch_log", {BLOCK_LOG, 2} },
    // Leaves
    { "leaves", {BLOCK_LEAVES, 0} },
    { "oak_leaves", {BLOCK_LEAVES, 0} },
    { "spruce_leaves", {BLOCK_LEAVES, 1} },
    { "birch_leaves", {BLOCK_LEAVES, 2} },
    { "sponge", {BLOCK_SPONGE, 0} },
    { "glass", {BLOCK_GLASS, 0} },
    { "lapis_ore", {BLOCK_ORE_LAPIS_LAZULI, 0} },
    { "lapis_lazuli_ore", {BLOCK_ORE_LAPIS_LAZULI, 0} },
    { "lapis_block", {BLOCK_LAPIS_LAZULI, 0} },
    { "lapis_lazuli_block", {BLOCK_LAPIS_LAZULI, 0} },
    { "dispenser", {BLOCK_DISPENSER, 0} },
    { "sandstone", {BLOCK_SANDSTONE, 0} },
    { "note_block", {BLOCK_NOTEBLOCK, 0} },
    { "noteblock", {BLOCK_NOTEBLOCK, 0} },
    //{ "bed", {BLOCK_BED, 0} },
    { "powered_rail", {BLOCK_RAIL_POWERED, 0} },
    { "golden_rail", {BLOCK_RAIL_POWERED, 0} },
    { "detector_rail", {BLOCK_RAIL_DETECTOR, 0} },
    { "sticky_piston", {BLOCK_PISTON_STICKY, 0} },
    { "cobweb", {BLOCK_COBWEB, 0} },
    { "shrub", {BLOCK_TALLGRASS, 0} },
    { "short_grass", {BLOCK_TALLGRASS, 1} },
    { "fern", {BLOCK_TALLGRASS, 2} },
    { "web", {BLOCK_COBWEB, 0} },
    { "deadbush", {BLOCK_DEADBUSH, 0} },
    { "dead_bush", {BLOCK_DEADBUSH, 0} },
    { "piston", {BLOCK_PISTON, 0} },
    { "piston_head", {BLOCK_PISTON_HEAD, 0} },
    // Wool
    { "wool", {BLOCK_WOOL, 0} },
    { "white_wool", {BLOCK_WOOL, 0} },
    { "orange_wool", {BLOCK_WOOL, 1} },
    { "magenta_wool", {BLOCK_WOOL, 2} },
    { "light_blue_wool", {BLOCK_WOOL, 3} },
    { "yellow_wool", {BLOCK_WOOL, 4} },
    { "lime_wool", {BLOCK_WOOL, 5} },
    { "pink_wool", {BLOCK_WOOL, 6} },
    { "gray_wool", {BLOCK_WOOL, 7} },
    { "light_gray_wool", {BLOCK_WOOL, 8} },
    { "cyan_wool", {BLOCK_WOOL, 9} },
    { "purple_wool", {BLOCK_WOOL, 10} },
    { "blue_wool", {BLOCK_WOOL, 11} },
    { "brown_wool", {BLOCK_WOOL, 12} },
    { "green_wool", {BLOCK_WOOL, 13} },
    { "red_wool", {BLOCK_WOOL, 14} },
    { "black_wool", {BLOCK_WOOL, 15} },
    { "moving_piston", {BLOCK_PISTON_MOVING, 0} },
    { "dandelion", {BLOCK_DANDELION, 0} },
    { "yellow_flower", {BLOCK_DANDELION, 0} },
    { "rose", {BLOCK_ROSE, 0} },
    { "red_flower", {BLOCK_ROSE, 0} },
    { "brown_mushroom", {BLOCK_MUSHROOM_BROWN, 0} },
    { "red_mushroom", {BLOCK_MUSHROOM_RED, 0} },
    { "gold_block", {BLOCK_GOLD, 0} },
    { "iron_block", {BLOCK_IRON, 0} },
    // Double slabs
    { "double_slab", {BLOCK_DOUBLE_SLAB, 0} },
    { "smooth_stone_double_slab", {BLOCK_DOUBLE_SLAB, 0} },
    { "stone_double_slab", {BLOCK_DOUBLE_SLAB, 0} },
    { "sandstone_double_slab", {BLOCK_DOUBLE_SLAB, 1} },
    { "wood_double_slab", {BLOCK_DOUBLE_SLAB, 2} },
    { "wooden_double_slab", {BLOCK_DOUBLE_SLAB, 2} },
    { "cobblestone_double_slab", {BLOCK_DOUBLE_SLAB, 3} },
    // Slab
    { "slab", {BLOCK_SLAB, 0} },
    { "smooth_stone_slab", {BLOCK_DOUBLE_SLAB, 0} },
    { "stone_slab", {BLOCK_SLAB, 0} },
    { "sandstone_slab", {BLOCK_SLAB, 1} },
    { "wood_slab", {BLOCK_SLAB, 2} },
    { "wooden_slab", {BLOCK_SLAB, 2} },
    { "cobblestone_slab", {BLOCK_SLAB, 3} },
    { "bricks", {BLOCK_BRICKS, 0} },
    { "tnt", {BLOCK_TNT, 0} },
    { "bookshelf", {BLOCK_BOOKSHELF, 0} },
    { "mossy_cobblestone", {BLOCK_COBBLESTONE_MOSSY, 0} },
    { "obsidian", {BLOCK_OBSIDIAN, 0} },
    { "torch", {BLOCK_TORCH, 0} },
    { "fire", {BLOCK_FIRE, 0} },
    { "spawner", {BLOCK_MOB_SPAWNER, 0} },
    { "mob_spawner", {BLOCK_MOB_SPAWNER, 0} },
    { "wood_stairs", {BLOCK_STAIRS_WOOD, 0} },
    { "wooden_stairs", {BLOCK_STAIRS_WOOD, 0} },
    { "wood_stair", {BLOCK_STAIRS_WOOD, 0} },
    { "wooden_stair", {BLOCK_STAIRS_WOOD, 0} },
    { "chest", {BLOCK_CHEST, 0} },
    //{ "redstone_wire", {BLOCK_REDSTONE, 0} },
    { "diamond_ore", {BLOCK_ORE_DIAMOND, 0} },
    { "diamond_block", {BLOCK_DIAMOND, 0} },
    { "crafting_table", {BLOCK_CRAFTING_TABLE, 0} },
    //{ "wheat_crop", {BLOCK_CROP_WHEAT, 0} },
    { "farmland", {BLOCK_FARMLAND, 0} },
    { "furnace", {BLOCK_FURNACE, 0} },
    { "lit_furnace", {BLOCK_FURNACE_LIT, 0} },
    //{ "standing_sign", {BLOCK_SIGN_STANDING, 0} },
    //{ "wood_door", {BLOCK_DOOR_WOOD, 0} },
    //{ "wooden_door", {BLOCK_DOOR_WOOD, 0} },
    { "ladder", {BLOCK_LADDER, 0} },
    { "rail", {BLOCK_RAIL, 0} },
    { "cobblestone_stairs", {BLOCK_STAIRS_COBBLESTONE, 0} },
    { "cobblestone_stair", {BLOCK_STAIRS_COBBLESTONE, 0} },
    //{ "wall_sign", {BLOCK_SIGN_WALL, 0} },
    { "lever", {BLOCK_LEVER, 0} },
    { "stone_pressure_plate", {BLOCK_PRESSURE_PLATE_STONE, 0} },
    //{ "iron_door", {BLOCK_DOOR_IRON, 0} },
    { "wood_pressure_plate", {BLOCK_PRESSURE_PLATE_WOOD, 0} },
    { "wooden_pressure_plate", {BLOCK_PRESSURE_PLATE_WOOD, 0} },
    { "redstone_ore", {BLOCK_ORE_REDSTONE_OFF, 0} },
    { "lit_redstone_ore", {BLOCK_ORE_REDSTONE_ON, 0} },
    //{ "redstone_torch", {BLOCK_REDSTONE_TORCH_OFF, 0} },
    { "redstone_torch", {BLOCK_REDSTONE_TORCH_ON, 0} },
    { "button", {BLOCK_BUTTON_STONE, 0} },
    { "stone_button", {BLOCK_BUTTON_STONE, 0} },
    // This is JE accurate. On Bedrock this'd be a snow block. Confusing...
    { "snow", {BLOCK_SNOW_LAYER, 0} },
    { "snow_layer", {BLOCK_SNOW_LAYER, 0} },
    { "ice", {BLOCK_ICE, 0} },
    { "snow_block", {BLOCK_SNOW, 0} },
    { "cactus", {BLOCK_CACTUS, 0} },
    { "clay", {BLOCK_CLAY, 0} },
    //{ "reeds", {BLOCK_SUGARCANE, 0} },
    //{ "sugar_cane", {BLOCK_SUGARCANE, 0} },
    { "jukebox", {BLOCK_JUKEBOX, 0} },
    { "fence", {BLOCK_FENCE, 0} },
    { "pumpkin", {BLOCK_PUMPKIN, 0} },
    { "netherrack", {BLOCK_NETHERRACK, 0} },
    { "soul_sand", {BLOCK_SOULSAND, 0} },
    { "glowstone", {BLOCK_GLOWSTONE, 0} },
    { "portal", {BLOCK_NETHER_PORTAL, 0} },
    { "nether_portal", {BLOCK_NETHER_PORTAL, 0} },
    { "lit_pumpkin", {BLOCK_PUMPKIN_LIT, 0} },
    { "jack_o_lantern", {BLOCK_PUMPKIN_LIT, 0} },
    //{ "cake", {BLOCK_CAKE, 0} },
    //{ "unpowered_repeater", {BLOCK_REDSTONE_REPEATER_OFF, 0} },
    //{ "powered_repeater", {BLOCK_REDSTONE_REPEATER_ON, 0} },
    // Technically "chest_locked_aprilfools_super_old_legacy_we_should_not_even_have_this" would also be correct lol
    { "chest_locked", {BLOCK_CHEST_LOCKED, 0} },
    { "locked_chest", {BLOCK_CHEST_LOCKED, 0} },
    { "trapdoor", {BLOCK_TRAPDOOR, 0} },

    // Items
    { "iron_shovel", {Items::Id::SHOVEL_IRON, 0} },
    { "iron_pickaxe", {Items::Id::PICKAXE_IRON, 0} },
    { "iron_axe", {Items::Id::AXE_IRON, 0} },
    { "flint_and_steel", {Items::Id::FLINT_AND_STEEL, 0} },
    { "apple", {Items::Id::APPLE, 0} },
    { "bow", {Items::Id::BOW, 0} },
    { "arrow", {Items::Id::ARROW, 0} },
    { "coal", {Items::Id::COAL, 0} },
    { "diamond", {Items::Id::DIAMOND, 0} },
    { "iron", {Items::Id::IRON, 0} },
    { "iron_ingot", {Items::Id::IRON, 0} },
    { "gold", {Items::Id::GOLD, 0} },
    { "gold_ingot", {Items::Id::GOLD, 0} },
    { "iron_sword", {Items::Id::SWORD_IRON, 0} },
    // Wooden tools
    { "wood_sword", {Items::Id::SWORD_WOOD, 0} },
    { "wooden_sword", {Items::Id::SWORD_WOOD, 0} },
    { "wood_shovel", {Items::Id::SHOVEL_WOOD, 0} },
    { "wooden_shovel", {Items::Id::SHOVEL_WOOD, 0} },
    { "wood_pickaxe", {Items::Id::PICKAXE_WOOD, 0} },
    { "wooden_pickaxe", {Items::Id::PICKAXE_WOOD, 0} },
    { "wood_axe", {Items::Id::AXE_WOOD, 0} },
    { "wooden_axe", {Items::Id::AXE_WOOD, 0} },
    // Stone tools
    { "stone_sword", {Items::Id::SWORD_STONE, 0} },
    { "stone_shovel", {Items::Id::SHOVEL_STONE, 0} },
    { "stone_pickaxe", {Items::Id::PICKAXE_STONE, 0} },
    { "stone_axe", {Items::Id::AXE_STONE, 0} },
    // Diamond tools
    { "diamond_sword", {Items::Id::SWORD_DIAMOND, 0} },
    { "diamond_shovel", {Items::Id::SHOVEL_DIAMOND, 0} },
    { "diamond_pickaxe", {Items::Id::PICKAXE_DIAMOND, 0} },
    { "diamond_axe", {Items::Id::AXE_DIAMOND, 0} },
    { "stick", {Items::Id::STICK, 0} },
    { "bowl", {Items::Id::BOWL, 0} },
    { "mushroom_stew", {Items::Id::MUSHROOM_STEW, 0} },
    // Gold tools
    { "gold_sword", {Items::Id::SWORD_GOLD, 0} },
    { "gold_shovel", {Items::Id::SHOVEL_GOLD, 0} },
    { "gold_pickaxe", {Items::Id::PICKAXE_GOLD, 0} },
    { "gold_axe", {Items::Id::AXE_GOLD, 0} },
    { "string", {Items::Id::STRING, 0} },
    { "feather", {Items::Id::FEATHER, 0} },
    { "sulfur", {Items::Id::GUNPOWDER, 0} },
    { "sulphur", {Items::Id::GUNPOWDER, 0} },
    { "gunpowder", {Items::Id::GUNPOWDER, 0} },
    // Hoes
    { "wood_hoe", {Items::Id::HOE_WOOD, 0} },
    { "wooden_hoe", {Items::Id::HOE_WOOD, 0} },
    { "stone_hoe", {Items::Id::HOE_STONE, 0} },
    { "iron_hoe", {Items::Id::HOE_IRON, 0} },
    { "diamond_hoe", {Items::Id::HOE_DIAMOND, 0} },
    { "gold_hoe", {Items::Id::HOE_GOLD, 0} },
    // Wheat
    { "seeds", {Items::Id::SEEDS_WHEAT, 0} },
    { "wheat_seeds", {Items::Id::SEEDS_WHEAT, 0} },
    { "wheat", {Items::Id::WHEAT, 0} },
    { "wheat", {Items::Id::WHEAT, 0} },
    { "bread", {Items::Id::BREAD, 0} },
    // Armor
    // Leather
    { "leather_cap", {Items::Id::HELMET_LEATHER, 0} },
    { "leather_helmet", {Items::Id::HELMET_LEATHER, 0} },
    { "leather_tunic", {Items::Id::CHESTPLATE_LEATHER, 0} },
    { "leather_chestplate", {Items::Id::CHESTPLATE_LEATHER, 0} },
    { "leather_pants", {Items::Id::LEGGINGS_LEATHER, 0} },
    { "leather_leggings", {Items::Id::LEGGINGS_LEATHER, 0} },
    { "leather_boots", {Items::Id::BOOTS_LEATHER, 0} },
    // Chainmail
    { "chainmail_helmet", {Items::Id::HELMET_CHAINMAIL, 0} },
    { "chainmail_chestplate", {Items::Id::CHESTPLATE_CHAINMAIL, 0} },
    { "chainmail_leggings", {Items::Id::LEGGINGS_CHAINMAIL, 0} },
    { "chainmail_boots", {Items::Id::BOOTS_CHAINMAIL, 0} },
    // Iron
    { "iron_helmet", {Items::Id::HELMET_IRON, 0} },
    { "iron_chestplate", {Items::Id::CHESTPLATE_IRON, 0} },
    { "iron_leggings", {Items::Id::LEGGINGS_IRON, 0} },
    { "iron_boots", {Items::Id::BOOTS_IRON, 0} },
    // Diamond
    { "diamond_helmet", {Items::Id::HELMET_DIAMOND, 0} },
    { "diamond_chestplate", {Items::Id::CHESTPLATE_DIAMOND, 0} },
    { "diamond_leggings", {Items::Id::LEGGINGS_DIAMOND, 0} },
    { "diamond_boots", {Items::Id::BOOTS_DIAMOND, 0} },
    // Gold
    { "gold_helmet", {Items::Id::HELMET_GOLD, 0} },
    { "gold_chestplate", {Items::Id::CHESTPLATE_GOLD, 0} },
    { "gold_leggings", {Items::Id::LEGGINGS_GOLD, 0} },
    { "gold_boots", {Items::Id::BOOTS_GOLD, 0} },
    { "flint", {Items::Id::FLINT, 0} },
    { "porkchop", {Items::Id::PORKCHOP, 0} },
    { "raw_porkchop", {Items::Id::PORKCHOP, 0} },
    { "cooked_porkchop", {Items::Id::PORKCHOP_COOKED, 0} },
    { "painting", {Items::Id::PAINTING, 0} },
    { "golden_apple", {Items::Id::APPLE_GOLDEN, 0} },
    { "sign", {Items::Id::SIGN, 0} },
    { "wood_door", {Items::Id::DOOR_WOOD, 0} },
    { "wooden_door", {Items::Id::DOOR_WOOD, 0} },
    { "bucket", {Items::Id::BUCKET, 0} },
    { "empty_bucket", {Items::Id::BUCKET, 0} },
    { "water_bucket", {Items::Id::BUCKET_WATER, 0} },
    { "lava_bucket", {Items::Id::BUCKET_LAVA, 0} },
    { "minecart", {Items::Id::MINECART, 0} },
    { "saddle", {Items::Id::SADDLE, 0} },
    { "iron_door", {Items::Id::DOOR_IRON, 0} },
    { "redstone", {Items::Id::REDSTONE, 0} },
    { "snowball", {Items::Id::SNOWBALL, 0} },
    { "boat", {Items::Id::BOAT, 0} },
    { "leather", {Items::Id::LEATHER, 0} },
    { "milk_bucket", {Items::Id::BUCKET_MILK, 0} },
    { "brick", {Items::Id::BRICK, 0} },
    { "clay_ball", {Items::Id::CLAY, 0} },
    { "reeds", {Items::Id::SUGARCANE, 0} },
    { "sugar_cane", {Items::Id::SUGARCANE, 0} },
    { "paper", {Items::Id::PAPER, 0} },
    { "book", {Items::Id::BOOK, 0} },
    { "slime", {Items::Id::SLIME, 0} },
    { "chest_minecart", {Items::Id::MINECART_CHEST, 0} },
    { "furnace_minecart", {Items::Id::MINECART_FURNACE, 0} },
    { "egg", {Items::Id::EGG, 0} },
    { "compass", {Items::Id::COMPASS, 0} },
    { "fishing_rod", {Items::Id::FISHING_ROD, 0} },
    { "clock", {Items::Id::CLOCK, 0} },
    { "glowstone_dust", {Items::Id::GLOWSTONE_DUST, 0} },
    { "fish", {Items::Id::FISH, 0} },
    { "cooked_fish", {Items::Id::FISH_COOKED, 0} },
    // Dyes
    { "dye", {Items::Id::DYE, 0} },
    { "ink_sac", {Items::Id::DYE, 0} },
    { "black_dye", {Items::Id::DYE, 0} },
    { "red_dye", {Items::Id::DYE, 1} },
    { "green_dye", {Items::Id::DYE, 2} },
    { "brown_dye", {Items::Id::DYE, 3} },
    { "cocoa_beans", {Items::Id::DYE, 3} },
    { "blue_dye", {Items::Id::DYE, 4} },
    { "lapis_lazuli", {Items::Id::DYE, 4} },
    { "purple_dye", {Items::Id::DYE, 5} },
    { "cyan_dye", {Items::Id::DYE, 6} },
    { "light_gray_dye", {Items::Id::DYE, 7} },
    { "gray_dye", {Items::Id::DYE, 8} },
    { "pink_dye", {Items::Id::DYE, 9} },
    { "lime_dye", {Items::Id::DYE, 10} },
    { "yellow_dye", {Items::Id::DYE, 11} },
    { "light_blue_dye", {Items::Id::DYE, 12} },
    { "magenta_dye", {Items::Id::DYE, 13} },
    { "orange_dye", {Items::Id::DYE, 14} },
    { "white_dye", {Items::Id::DYE, 15} },
    { "bonemeal", {Items::Id::DYE, 15} },
    { "bone_meal", {Items::Id::DYE, 15} },
    { "bone", {Items::Id::BONE, 0} },
    { "sugar", {Items::Id::SUGAR, 0} },
    { "cake", {Items::Id::CAKE, 0} },
    { "bed", {Items::Id::BED, 0} },
    { "repeater", {Items::Id::REDSTONE_REPEATER, 0} },
    { "redstone_repeater", {Items::Id::REDSTONE_REPEATER, 0} },
    { "cookie", {Items::Id::COOKIE, 0} },
    { "map", {Items::Id::MAP, 0} },
    { "shears", {Items::Id::SHEARS, 0} },
    { "record_13", {Items::Id::RECORD_13, 0} },
    { "music_disc_13", {Items::Id::RECORD_13, 0} },
    { "record_cat", {Items::Id::RECORD_CAT, 0} },
    { "music_disc_cat", {Items::Id::RECORD_CAT, 0} },
};