/*
 * Copyright (c) 2026, Pixel Brush <pixelbrush.dev>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 *
*/

// This file is primarily used by commands, so someone doesn't need to remember all the ids
// The labels chosen here will match those used by modern Minecraft,
// as those are the ones most people are likely the know best.
// It will deviate a little if the modern label doesn't fit the old block (e.g. "oak_planks" VS just "planks")

#include "../inventory/item_stack.h"
#include "../enums/blocks.h"
#include <unordered_map>
#include <string>


#pragma once

// TODO: Some of these will need to be renamed for made unobtainable
// like this so stuff doesn't conflict with their item forms

std::unordered_map<std::string, ItemStack> identifierToId = {
    { "air", {BLOCK_AIR, 1, 0} },
    { "stone", {BLOCK_STONE, 1, 0} },
    { "grass_block", {BLOCK_GRASS, 1, 0} },
    { "dirt", {BLOCK_DIRT, 1, 0} },
    { "cobblestone", {BLOCK_COBBLESTONE, 1, 0} },
    { "planks", {BLOCK_PLANKS, 1, 0} },
    // Saplings
    { "sapling", {BLOCK_SAPLING, 1, 0} },
    { "oak_sapling", {BLOCK_SAPLING, 1, 0} },
    { "spruce_sapling", {BLOCK_SAPLING, 1, 1} },
    { "birch_sapling", {BLOCK_SAPLING, 1, 2} },
    { "bedrock", {BLOCK_BEDROCK, 1, 0} },
    { "flowing_water", {BLOCK_WATER_FLOWING, 1, 0} },
    { "water", {BLOCK_WATER_STILL, 1, 0} },
    { "flowing_lava", {BLOCK_LAVA_FLOWING, 1, 0} },
    { "lava", {BLOCK_LAVA_STILL, 1, 0} },
    { "sand", {BLOCK_SAND, 1, 0} },
    { "gravel", {BLOCK_GRAVEL, 1, 0} },
    { "gold_ore", {BLOCK_ORE_GOLD, 1, 0} },
    { "iron_ore", {BLOCK_ORE_IRON, 1, 0} },
    { "coal_ore", {BLOCK_ORE_COAL, 1, 0} },
    // Logs
    { "log", {BLOCK_LOG, 1, 0} },
    { "oak_log", {BLOCK_LOG, 1, 0} },
    { "spruce_log", {BLOCK_LOG, 1, 1} },
    { "birch_log", {BLOCK_LOG, 1, 2} },
    // Leaves
    { "leaves", {BLOCK_LEAVES, 1, 0} },
    { "oak_leaves", {BLOCK_LEAVES, 1, 0} },
    { "spruce_leaves", {BLOCK_LEAVES, 1, 1} },
    { "birch_leaves", {BLOCK_LEAVES, 1, 2} },
    { "sponge", {BLOCK_SPONGE, 1, 0} },
    { "glass", {BLOCK_GLASS, 1, 0} },
    { "lapis_ore", {BLOCK_ORE_LAPIS_LAZULI, 1, 0} },
    { "lapis_block", {BLOCK_LAPIS_LAZULI, 1, 0} },
    { "dispenser", {BLOCK_DISPENSER, 1, 0} },
    { "sandstone", {BLOCK_SANDSTONE, 1, 0} },
    { "note_block", {BLOCK_NOTEBLOCK, 1, 0} },
    { "noteblock", {BLOCK_NOTEBLOCK, 1, 0} },
    { "bed", {BLOCK_BED, 1, 0} },
    { "powered_rail", {BLOCK_RAIL_POWERED, 1, 0} },
    { "golden_rail", {BLOCK_RAIL_POWERED, 1, 0} },
    { "detector_rail", {BLOCK_RAIL_DETECTOR, 1, 0} },
    { "sticky_piston", {BLOCK_PISTON_STICKY, 1, 0} },
    { "cobweb", {BLOCK_COBWEB, 1, 0} },
    { "shrub", {BLOCK_TALLGRASS, 1, 0} },
    { "short_grass", {BLOCK_TALLGRASS, 1, 1} },
    { "fern", {BLOCK_TALLGRASS, 1, 2} },
    { "web", {BLOCK_COBWEB, 1, 0} },
    { "deadbush", {BLOCK_DEADBUSH, 1, 0} },
    { "dead_bush", {BLOCK_DEADBUSH, 1, 0} },
    { "piston", {BLOCK_PISTON, 1, 0} },
    { "piston_head", {BLOCK_PISTON_HEAD, 1, 0} },
    // Wool
    { "wool", {BLOCK_WOOL, 1, 0} },
    { "white_wool", {BLOCK_WOOL, 1, 0} },
    { "orange_wool", {BLOCK_WOOL, 1, 1} },
    { "magenta_wool", {BLOCK_WOOL, 1, 2} },
    { "light_blue_wool", {BLOCK_WOOL, 1, 3} },
    { "yellow_wool", {BLOCK_WOOL, 1, 4} },
    { "lime_wool", {BLOCK_WOOL, 1, 5} },
    { "pink_wool", {BLOCK_WOOL, 1, 6} },
    { "gray_wool", {BLOCK_WOOL, 1, 7} },
    { "light_gray_wool", {BLOCK_WOOL, 1, 8} },
    { "cyan_wool", {BLOCK_WOOL, 1, 9} },
    { "purple_wool", {BLOCK_WOOL, 1, 10} },
    { "blue_wool", {BLOCK_WOOL, 1, 11} },
    { "brown_wool", {BLOCK_WOOL, 1, 12} },
    { "green_wool", {BLOCK_WOOL, 1, 13} },
    { "red_wool", {BLOCK_WOOL, 1, 14} },
    { "black_wool", {BLOCK_WOOL, 1, 15} },
    { "moving_piston", {BLOCK_PISTON_MOVING, 1, 0} },
    { "dandelion", {BLOCK_DANDELION, 1, 0} },
    { "yellow_flower", {BLOCK_DANDELION, 1, 0} },
    { "rose", {BLOCK_ROSE, 1, 0} },
    { "red_flower", {BLOCK_ROSE, 1, 0} },
    { "brown_mushroom", {BLOCK_MUSHROOM_BROWN, 1, 0} },
    { "red_mushroom", {BLOCK_MUSHROOM_RED, 1, 0} },
    { "gold_block", {BLOCK_GOLD, 1, 0} },
    { "iron_block", {BLOCK_IRON, 1, 0} },
    // Double slabs
    { "double_slab", {BLOCK_DOUBLE_SLAB, 1, 0} },
    { "smooth_stone_double_slab", {BLOCK_DOUBLE_SLAB, 1, 0} },
    { "stone_double_slab", {BLOCK_DOUBLE_SLAB, 1, 0} },
    { "sandstone_double_slab", {BLOCK_DOUBLE_SLAB, 1, 1} },
    { "wood_double_slab", {BLOCK_DOUBLE_SLAB, 1, 2} },
    { "wooden_double_slab", {BLOCK_DOUBLE_SLAB, 1, 2} },
    { "cobblestone_double_slab", {BLOCK_DOUBLE_SLAB, 1, 3} },
    // Slab
    { "slab", {BLOCK_SLAB, 1, 0} },
    { "smooth_stone_slab", {BLOCK_DOUBLE_SLAB, 1, 0} },
    { "stone_slab", {BLOCK_SLAB, 1, 0} },
    { "sandstone_slab", {BLOCK_SLAB, 1, 1} },
    { "wood_slab", {BLOCK_SLAB, 1, 2} },
    { "wooden_slab", {BLOCK_SLAB, 1, 2} },
    { "cobblestone_slab", {BLOCK_SLAB, 1, 3} },
    { "bricks", {BLOCK_BRICKS, 1, 0} },
    { "tnt", {BLOCK_TNT, 1, 0} },
    { "bookshelf", {BLOCK_BOOKSHELF, 1, 0} },
    { "mossy_cobblestone", {BLOCK_COBBLESTONE_MOSSY, 1, 0} },
    { "obsidian", {BLOCK_OBSIDIAN, 1, 0} },
    { "torch", {BLOCK_TORCH, 1, 0} },
    { "fire", {BLOCK_FIRE, 1, 0} },
    { "spawner", {BLOCK_MOB_SPAWNER, 1, 0} },
    { "mob_spawner", {BLOCK_MOB_SPAWNER, 1, 0} },
    { "wood_stairs", {BLOCK_STAIRS_WOOD, 1, 0} },
    { "wooden_stairs", {BLOCK_STAIRS_WOOD, 1, 0} },
    { "chest", {BLOCK_CHEST, 1, 0} },
    { "redstone_wire", {BLOCK_REDSTONE, 1, 0} },
    { "diamond_ore", {BLOCK_ORE_DIAMOND, 1, 0} },
    { "diamond_block", {BLOCK_DIAMOND, 1, 0} },
    { "crafting_table", {BLOCK_CRAFTING_TABLE, 1, 0} },
    { "wheat_crop", {BLOCK_CROP_WHEAT, 1, 0} },
    { "farmland", {BLOCK_FARMLAND, 1, 0} },
    { "furnace", {BLOCK_FURNACE, 1, 0} },
    { "lit_furnace", {BLOCK_FURNACE_LIT, 1, 0} },
    { "standing_sign", {BLOCK_SIGN_STANDING, 1, 0} },
    { "wood_door", {BLOCK_DOOR_WOOD, 1, 0} },
    { "wooden_door", {BLOCK_DOOR_WOOD, 1, 0} },
    { "ladder", {BLOCK_LADDER, 1, 0} },
    { "rail", {BLOCK_RAIL, 1, 0} },
    { "cobblestone_stairs", {BLOCK_STAIRS_COBBLESTONE, 1, 0} },
    { "wall_sign", {BLOCK_SIGN_WALL, 1, 0} },
    { "lever", {BLOCK_LEVER, 1, 0} },
    { "stone_pressure_plate", {BLOCK_PRESSURE_PLATE_STONE, 1, 0} },
    { "iron_door", {BLOCK_DOOR_IRON, 1, 0} },
    { "wood_pressure_plate", {BLOCK_PRESSURE_PLATE_WOOD, 1, 0} },
    { "wooden_pressure_plate", {BLOCK_PRESSURE_PLATE_WOOD, 1, 0} },
    { "redstone_ore", {BLOCK_ORE_REDSTONE_OFF, 1, 0} },
    { "lit_redstone_ore", {BLOCK_ORE_REDSTONE_ON, 1, 0} },
    { "redstone_torch", {BLOCK_REDSTONE_TORCH_OFF, 1, 0} },
    { "lit_redstone_torch", {BLOCK_REDSTONE_TORCH_ON, 1, 0} },
    { "button", {BLOCK_BUTTON_STONE, 1, 0} },
    { "stone_button", {BLOCK_BUTTON_STONE, 1, 0} },
    // This is JE accurate. On Bedrock this'd be a snow block. Confusing...
    { "snow", {BLOCK_SNOW_LAYER, 1, 0} },
    { "snow_layer", {BLOCK_SNOW_LAYER, 1, 0} },
    { "ice", {BLOCK_ICE, 1, 0} },
    { "snow_block", {BLOCK_SNOW, 1, 0} },
    { "cactus", {BLOCK_CACTUS, 1, 0} },
    { "clay", {BLOCK_CLAY, 1, 0} },
    { "reeds", {BLOCK_SUGARCANE, 1, 0} },
    { "sugar_cane", {BLOCK_SUGARCANE, 1, 0} },
    { "jukebox", {BLOCK_JUKEBOX, 1, 0} },
    { "fence", {BLOCK_FENCE, 1, 0} },
    { "pumpkin", {BLOCK_PUMPKIN, 1, 0} },
    { "netherrack", {BLOCK_NETHERRACK, 1, 0} },
    { "soul_sand", {BLOCK_SOULSAND, 1, 0} },
    { "glowstone", {BLOCK_GLOWSTONE, 1, 0} },
    { "portal", {BLOCK_NETHER_PORTAL, 1, 0} },
    { "nether_portal", {BLOCK_NETHER_PORTAL, 1, 0} },
    { "lit_pumpkin", {BLOCK_PUMPKIN_LIT, 1, 0} },
    { "jack_o_lantern", {BLOCK_PUMPKIN_LIT, 1, 0} },
    { "cake", {BLOCK_CAKE, 1, 0} },
    { "unpowered_repeater", {BLOCK_REDSTONE_REPEATER_OFF, 1, 0} },
    { "powered_repeater", {BLOCK_REDSTONE_REPEATER_ON, 1, 0} },
    // Technically "chest_locked_aprilfools_super_old_legacy_we_should_not_even_have_this" would also be correct lol
    { "chest_locked", {BLOCK_CHEST_LOCKED, 1, 0} },
    { "locked_chest", {BLOCK_CHEST_LOCKED, 1, 0} },
    { "trapdoor", {BLOCK_TRAPDOOR, 1, 0} },
};