name: Run TODO to Issue
on:
  push:
    paths:
      - 'src/**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v6
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5
        env:
          MANUAL_COMMIT_REF: HEAD
          MANUAL_BASE_REF: 4ba1ff79a71221ada81dec291c98e277f14b3f63
        with:
          IGNORE: '^(?!src/)'